/**
 * ╔══════════════════════════════════════════════════════════════════════════════╗
 * ║                    SETTINGS STORE v3.2.0 ULTIMATE NEXUS                       ║
 * ║                    OMNIPOTENT SOVEREIGN EDITION                              ║
 * ╠══════════════════════════════════════════════════════════════════════════════╣
 * ║  Author: RAJSARASWATI JATAV (RS) - T3rmuxk1ng                                ║
 * ║  Description: Enhanced settings state management with Zustand                 ║
 * ║  Features: Categories, validation, persistence, defaults, shortcuts          ║
 * ╚══════════════════════════════════════════════════════════════════════════════╝
 * 
 * @module store/settingsStore
 * @version 3.2.0
 * @author RAJSARASWATI JATAV (RS)
 */

import { create } from 'zustand';
import { immer } from 'zustand/middleware/immer';
import { persist, createJSONStorage } from 'zustand/middleware';
import { VideoQuality, AudioQuality, VideoFormat, AudioFormat } from '@/types/api';

// ═══════════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Download settings interface
 */
export interface DownloadSettings {
  defaultOutputDir: string;
  defaultVideoQuality: VideoQuality;
  defaultAudioQuality: AudioQuality;
  defaultVideoFormat: VideoFormat;
  defaultAudioFormat: AudioFormat;
  maxConcurrentDownloads: number;
  autoStartDownloads: boolean;
  overwriteExisting: boolean;
  maxSpeed: number;
  retryAttempts: number;
  timeout: number;
  autoRetry: boolean;
  retryDelay: number;
  splitSize: number;
  useAria2: boolean;
  aria2Connections: number;
}

/**
 * Subtitle settings interface
 */
export interface SubtitleSettings {
  enabled: boolean;
  defaultLanguages: string[];
  embedInVideo: boolean;
  format: 'srt' | 'vtt' | 'ass';
  autoTranslate: boolean;
  translationTargetLang: string;
  preferAutoGenerated: boolean;
}

/**
 * Metadata settings interface
 */
export interface MetadataSettings {
  embedMetadata: boolean;
  embedThumbnail: boolean;
  saveThumbnail: boolean;
  thumbnailQuality: number;
  writeInfoJson: boolean;
  addChapters: boolean;
  embedCoverArt: boolean;
}

/**
 * Network settings interface
 */
export interface NetworkSettings {
  proxy: string;
  useProxy: boolean;
  customHeaders: Record<string, string>;
  cookies: string;
  userAgent: string;
  referer: string;
  connectionTimeout: number;
  readTimeout: number;
  dnsCache: boolean;
  ipv4Only: boolean;
}

/**
 * Theme settings interface
 */
export interface ThemeSettings {
  mode: 'light' | 'dark' | 'system';
  accentColor: string;
  customColors: {
    primary: string;
    secondary: string;
    background: string;
    surface: string;
    text: string;
    error: string;
    success: string;
    warning: string;
  };
  fontScale: number;
  fontFamily: string;
  borderRadius: number;
  animationsEnabled: boolean;
  blurEffects: boolean;
  transparency: number;
  customCSS: string;
}

/**
 * Keyboard shortcut interface
 */
export interface KeyboardShortcut {
  id: string;
  name: string;
  description: string;
  category: 'download' | 'navigation' | 'ui' | 'edit' | 'media';
  key: string;
  modifiers: ('ctrl' | 'alt' | 'shift' | 'meta')[];
  enabled: boolean;
  action: () => void;
}

/**
 * Keyboard shortcuts configuration
 */
export interface KeyboardShortcutsConfig {
  enabled: boolean;
  globalShortcuts: boolean;
  preventBrowserDefault: boolean;
  shortcuts: KeyboardShortcut[];
}

/**
 * Notification settings interface
 */
export interface NotificationSettings {
  enabled: boolean;
  position: 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left' | 'center';
  duration: number;
  soundEnabled: boolean;
  soundVolume: number;
  soundFile: string;
  desktopNotifications: boolean;
  notifyOnComplete: boolean;
  notifyOnError: boolean;
  notifyOnStart: boolean;
  notifyOnQueueComplete: boolean;
  maxVisible: number;
  pauseOnHover: boolean;
  showProgress: boolean;
  groupSimilar: boolean;
}

/**
 * History settings interface
 */
export interface HistorySettings {
  enabled: boolean;
  maxItems: number;
  autoCleanup: boolean;
  cleanupDays: number;
  rememberLastPath: boolean;
  lastPaths: string[];
  trackBandwidth: boolean;
}

/**
 * Security settings interface
 */
export interface SecuritySettings {
  apiKey: string;
  useAuth: boolean;
  sessionTimeout: number;
  encryptSettings: boolean;
  clearClipboardDelay: number;
  autoLock: boolean;
  lockTimeout: number;
}

/**
 * Advanced settings interface
 */
export interface AdvancedSettings {
  debugMode: boolean;
  logLevel: 'debug' | 'info' | 'warn' | 'error';
  logToFile: boolean;
  logFilePath: string;
  maxLogSize: number;
  updateChannel: 'stable' | 'beta' | 'dev';
  autoUpdate: boolean;
  experimentalFeatures: boolean;
  cacheEnabled: boolean;
  cacheSize: number;
  tempDir: string;
}

/**
 * UI preferences interface
 */
export interface UIPreferences {
  compactMode: boolean;
  showAdvancedOptions: boolean;
  showStatusBar: boolean;
  showToolbar: boolean;
  showSidebar: boolean;
  sidebarPosition: 'left' | 'right';
  sidebarWidth: number;
  defaultView: 'grid' | 'list' | 'compact';
  showFileSizes: boolean;
  showSpeed: boolean;
  showETA: boolean;
  showProgress: boolean;
  showThumbnails: boolean;
  thumbnailSize: number;
  confirmOnExit: boolean;
  confirmOnDelete: boolean;
  minimizeToTray: boolean;
  closeToTray: boolean;
  startMinimized: boolean;
  checkForUpdates: boolean;
  language: string;
  dateFormat: string;
  timeFormat: '12h' | '24h';
  numberFormat: string;
}

/**
 * Complete application settings
 */
export interface AppSettings {
  download: DownloadSettings;
  subtitles: SubtitleSettings;
  metadata: MetadataSettings;
  network: NetworkSettings;
  theme: ThemeSettings;
  shortcuts: KeyboardShortcutsConfig;
  notifications: NotificationSettings;
  history: HistorySettings;
  security: SecuritySettings;
  advanced: AdvancedSettings;
  ui: UIPreferences;
}

/**
 * Settings profile
 */
export interface SettingsProfile {
  id: string;
  name: string;
  description?: string;
  settings: Partial<AppSettings>;
  createdAt: Date;
  updatedAt: Date;
  isDefault: boolean;
}

/**
 * Settings validation result
 */
export interface ValidationResult {
  valid: boolean;
  errors: { path: string; message: string }[];
  warnings: { path: string; message: string }[];
}

/**
 * Undo/redo state
 */
interface UndoState {
  settings: Partial<AppSettings>;
  timestamp: number;
  action: string;
}

/**
 * Store state interface
 */
export interface SettingsStoreState {
  settings: AppSettings;
  profiles: SettingsProfile[];
  activeProfileId: string | null;
  isDirty: boolean;
  lastSaved: Date | null;
  lastModified: Date | null;
  undoStack: UndoState[];
  redoStack: UndoState[];
  maxUndoSteps: number;
  isHydrated: boolean;
}

/**
 * Store actions interface
 */
export interface SettingsStoreActions {
  // Settings actions
  setSettings: (settings: AppSettings) => void;
  updateSettings: <K extends keyof AppSettings>(
    category: K,
    updates: Partial<AppSettings[K]>
  ) => void;
  updateNestedSetting: (path: string, value: unknown) => void;
  resetToDefaults: () => void;
  resetCategory: <K extends keyof AppSettings>(category: K) => void;
  
  // Profile actions
  createProfile: (name: string, description?: string) => string;
  updateProfile: (id: string, updates: Partial<SettingsProfile>) => void;
  deleteProfile: (id: string) => void;
  activateProfile: (id: string) => void;
  duplicateProfile: (id: string) => string;
  exportProfile: (id: string) => string;
  importProfile: (data: string) => string | null;
  
  // Validation
  validateSettings: () => ValidationResult;
  validateCategory: <K extends keyof AppSettings>(category: K) => ValidationResult;
  
  // Keyboard shortcuts
  registerShortcut: (shortcut: Omit<KeyboardShortcut, 'id'>) => string;
  updateShortcut: (id: string, updates: Partial<KeyboardShortcut>) => void;
  removeShortcut: (id: string) => void;
  resetShortcuts: () => void;
  getShortcutByKey: (key: string, modifiers: ('ctrl' | 'alt' | 'shift' | 'meta')[]) => KeyboardShortcut | undefined;
  
  // Theme
  setThemeMode: (mode: 'light' | 'dark' | 'system') => void;
  setAccentColor: (color: string) => void;
  setCustomColor: (name: keyof ThemeSettings['customColors'], color: string) => void;
  resetTheme: () => void;
  exportTheme: () => string;
  importTheme: (data: string) => boolean;
  
  // Notifications
  updateNotificationSettings: (updates: Partial<NotificationSettings>) => void;
  testNotification: () => void;
  
  // Persistence
  markSaved: () => void;
  saveToStorage: () => void;
  loadFromStorage: () => void;
  exportSettings: () => string;
  importSettings: (data: string) => boolean;
  
  // Undo/Redo
  undo: () => boolean;
  redo: () => boolean;
  canUndo: () => boolean;
  canRedo: () => boolean;
  clearHistory: () => void;
  
  // Hydration
  setHydrated: (hydrated: boolean) => void;
}

/**
 * Combined store type
 */
export type SettingsStore = SettingsStoreState & SettingsStoreActions;

// ═══════════════════════════════════════════════════════════════════════════════
// DEFAULT SETTINGS
// ═══════════════════════════════════════════════════════════════════════════════

export const DEFAULT_APP_SETTINGS: AppSettings = {
  download: {
    defaultOutputDir: '~/Downloads/RS-Toolkit',
    defaultVideoQuality: VideoQuality.Q1080P,
    defaultAudioQuality: AudioQuality.HIGH,
    defaultVideoFormat: VideoFormat.MP4,
    defaultAudioFormat: AudioFormat.MP3,
    maxConcurrentDownloads: 3,
    autoStartDownloads: true,
    overwriteExisting: false,
    maxSpeed: 0,
    retryAttempts: 3,
    timeout: 300,
    autoRetry: true,
    retryDelay: 5,
    splitSize: 0,
    useAria2: false,
    aria2Connections: 16,
  },
  subtitles: {
    enabled: true,
    defaultLanguages: ['en'],
    embedInVideo: false,
    format: 'srt',
    autoTranslate: false,
    translationTargetLang: 'en',
    preferAutoGenerated: false,
  },
  metadata: {
    embedMetadata: true,
    embedThumbnail: false,
    saveThumbnail: true,
    thumbnailQuality: 85,
    writeInfoJson: false,
    addChapters: false,
    embedCoverArt: true,
  },
  network: {
    proxy: '',
    useProxy: false,
    customHeaders: {},
    cookies: '',
    userAgent: '',
    referer: '',
    connectionTimeout: 30,
    readTimeout: 60,
    dnsCache: true,
    ipv4Only: false,
  },
  theme: {
    mode: 'system',
    accentColor: '#10b981',
    customColors: {
      primary: '#10b981',
      secondary: '#6366f1',
      background: '#0f172a',
      surface: '#1e293b',
      text: '#f8fafc',
      error: '#ef4444',
      success: '#22c55e',
      warning: '#f59e0b',
    },
    fontScale: 1,
    fontFamily: 'Inter, system-ui, sans-serif',
    borderRadius: 8,
    animationsEnabled: true,
    blurEffects: true,
    transparency: 0.8,
    customCSS: '',
  },
  shortcuts: {
    enabled: true,
    globalShortcuts: false,
    preventBrowserDefault: true,
    shortcuts: [
      { id: 'new_download', name: 'New Download', description: 'Start a new download', category: 'download', key: 'n', modifiers: ['ctrl'], enabled: true, action: () => {} },
      { id: 'pause_all', name: 'Pause All', description: 'Pause all active downloads', category: 'download', key: 'p', modifiers: ['ctrl', 'shift'], enabled: true, action: () => {} },
      { id: 'resume_all', name: 'Resume All', description: 'Resume all paused downloads', category: 'download', key: 'r', modifiers: ['ctrl', 'shift'], enabled: true, action: () => {} },
      { id: 'clear_completed', name: 'Clear Completed', description: 'Clear completed downloads', category: 'download', key: 'Delete', modifiers: ['ctrl'], enabled: true, action: () => {} },
      { id: 'toggle_sidebar', name: 'Toggle Sidebar', description: 'Show/hide the sidebar', category: 'ui', key: 'b', modifiers: ['ctrl'], enabled: true, action: () => {} },
      { id: 'search', name: 'Search', description: 'Open search', category: 'ui', key: 'f', modifiers: ['ctrl'], enabled: true, action: () => {} },
      { id: 'settings', name: 'Open Settings', description: 'Open settings panel', category: 'ui', key: ',', modifiers: ['ctrl'], enabled: true, action: () => {} },
      { id: 'toggle_theme', name: 'Toggle Theme', description: 'Switch between light/dark theme', category: 'ui', key: 't', modifiers: ['ctrl', 'shift'], enabled: true, action: () => {} },
      { id: 'undo', name: 'Undo', description: 'Undo last action', category: 'edit', key: 'z', modifiers: ['ctrl'], enabled: true, action: () => {} },
      { id: 'redo', name: 'Redo', description: 'Redo last undone action', category: 'edit', key: 'z', modifiers: ['ctrl', 'shift'], enabled: true, action: () => {} },
      { id: 'select_all', name: 'Select All', description: 'Select all items', category: 'edit', key: 'a', modifiers: ['ctrl'], enabled: true, action: () => {} },
      { id: 'copy', name: 'Copy', description: 'Copy selected', category: 'edit', key: 'c', modifiers: ['ctrl'], enabled: true, action: () => {} },
      { id: 'paste', name: 'Paste', description: 'Paste from clipboard', category: 'edit', key: 'v', modifiers: ['ctrl'], enabled: true, action: () => {} },
    ],
  },
  notifications: {
    enabled: true,
    position: 'bottom-right',
    duration: 5000,
    soundEnabled: true,
    soundVolume: 0.5,
    soundFile: 'default',
    desktopNotifications: true,
    notifyOnComplete: true,
    notifyOnError: true,
    notifyOnStart: false,
    notifyOnQueueComplete: true,
    maxVisible: 5,
    pauseOnHover: true,
    showProgress: true,
    groupSimilar: true,
  },
  history: {
    enabled: true,
    maxItems: 1000,
    autoCleanup: true,
    cleanupDays: 30,
    rememberLastPath: true,
    lastPaths: [],
    trackBandwidth: true,
  },
  security: {
    apiKey: '',
    useAuth: false,
    sessionTimeout: 3600,
    encryptSettings: false,
    clearClipboardDelay: 30,
    autoLock: false,
    lockTimeout: 300,
  },
  advanced: {
    debugMode: false,
    logLevel: 'info',
    logToFile: false,
    logFilePath: '',
    maxLogSize: 10,
    updateChannel: 'stable',
    autoUpdate: true,
    experimentalFeatures: false,
    cacheEnabled: true,
    cacheSize: 500,
    tempDir: '',
  },
  ui: {
    compactMode: false,
    showAdvancedOptions: false,
    showStatusBar: true,
    showToolbar: true,
    showSidebar: true,
    sidebarPosition: 'left',
    sidebarWidth: 280,
    defaultView: 'list',
    showFileSizes: true,
    showSpeed: true,
    showETA: true,
    showProgress: true,
    showThumbnails: true,
    thumbnailSize: 64,
    confirmOnExit: true,
    confirmOnDelete: true,
    minimizeToTray: false,
    closeToTray: false,
    startMinimized: false,
    checkForUpdates: true,
    language: 'en',
    dateFormat: 'YYYY-MM-DD',
    timeFormat: '24h',
    numberFormat: 'en-US',
  },
};

// ═══════════════════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════════

const generateId = (): string => `profile_${Date.now()}_${Math.random().toString(36).substring(2, 10)}`;

const createUndoSnapshot = (settings: Partial<AppSettings>, action: string): UndoState => ({
  settings: JSON.parse(JSON.stringify(settings)),
  timestamp: Date.now(),
  action,
});

const deepClone = <T>(obj: T): T => JSON.parse(JSON.stringify(obj));

// ═══════════════════════════════════════════════════════════════════════════════
// STORE IMPLEMENTATION
// ═══════════════════════════════════════════════════════════════════════════════

export const useSettingsStore = create<SettingsStore>()(
  persist(
    immer((set, get) => ({
      // ═════════════════════════════════════════════════════════════════════════
      // INITIAL STATE
      // ═════════════════════════════════════════════════════════════════════════
      settings: deepClone(DEFAULT_APP_SETTINGS),
      profiles: [],
      activeProfileId: null,
      isDirty: false,
      lastSaved: null,
      lastModified: null,
      undoStack: [],
      redoStack: [],
      maxUndoSteps: 50,
      isHydrated: false,

      // ═════════════════════════════════════════════════════════════════════════
      // SETTINGS ACTIONS
      // ═════════════════════════════════════════════════════════════════════════

      setSettings: (settings) => {
        set((state) => {
          state.undoStack.push(createUndoSnapshot(state.settings, 'setSettings'));
          if (state.undoStack.length > state.maxUndoSteps) {
            state.undoStack.shift();
          }
          state.redoStack = [];
          
          state.settings = settings;
          state.isDirty = true;
          state.lastModified = new Date();
        });
      },

      updateSettings: (category, updates) => {
        set((state) => {
          state.undoStack.push(createUndoSnapshot({ [category]: state.settings[category] }, `update ${String(category)}`));
          if (state.undoStack.length > state.maxUndoSteps) {
            state.undoStack.shift();
          }
          state.redoStack = [];
          
          state.settings[category] = {
            ...state.settings[category],
            ...updates,
          } as AppSettings[typeof category];
          state.isDirty = true;
          state.lastModified = new Date();
        });
      },

      updateNestedSetting: (path, value) => {
        set((state) => {
          const keys = path.split('.');
          let current: Record<string, unknown> = state.settings;
          
          for (let i = 0; i < keys.length - 1; i++) {
            current = current[keys[i]] as Record<string, unknown>;
          }
          
          current[keys[keys.length - 1]] = value;
          state.isDirty = true;
          state.lastModified = new Date();
        });
      },

      resetToDefaults: () => {
        set((state) => {
          state.undoStack.push(createUndoSnapshot(state.settings, 'resetToDefaults'));
          state.redoStack = [];
          
          state.settings = deepClone(DEFAULT_APP_SETTINGS);
          state.isDirty = true;
          state.lastModified = new Date();
        });
      },

      resetCategory: (category) => {
        set((state) => {
          state.undoStack.push(createUndoSnapshot({ [category]: state.settings[category] }, `reset ${String(category)}`));
          state.redoStack = [];
          
          state.settings[category] = deepClone(DEFAULT_APP_SETTINGS[category]);
          state.isDirty = true;
          state.lastModified = new Date();
        });
      },

      // ═════════════════════════════════════════════════════════════════════════
      // PROFILE ACTIONS
      // ═════════════════════════════════════════════════════════════════════════

      createProfile: (name, description) => {
        const id = generateId();
        set((state) => {
          state.profiles.push({
            id,
            name,
            description,
            settings: deepClone(state.settings),
            createdAt: new Date(),
            updatedAt: new Date(),
            isDefault: false,
          });
        });
        return id;
      },

      updateProfile: (id, updates) => {
        set((state) => {
          const index = state.profiles.findIndex((p) => p.id === id);
          if (index !== -1) {
            state.profiles[index] = {
              ...state.profiles[index],
              ...updates,
              updatedAt: new Date(),
            };
          }
        });
      },

      deleteProfile: (id) => {
        set((state) => {
          const profile = state.profiles.find((p) => p.id === id);
          if (profile && !profile.isDefault) {
            state.profiles = state.profiles.filter((p) => p.id !== id);
            if (state.activeProfileId === id) {
              state.activeProfileId = null;
            }
          }
        });
      },

      activateProfile: (id) => {
        set((state) => {
          const profile = state.profiles.find((p) => p.id === id);
          if (profile) {
            state.undoStack.push(createUndoSnapshot(state.settings, `activate profile: ${profile.name}`));
            state.redoStack = [];
            
            state.settings = { ...deepClone(DEFAULT_APP_SETTINGS), ...profile.settings };
            state.activeProfileId = id;
            state.isDirty = true;
          }
        });
      },

      duplicateProfile: (id) => {
        const newId = generateId();
        set((state) => {
          const profile = state.profiles.find((p) => p.id === id);
          if (profile) {
            state.profiles.push({
              ...profile,
              id: newId,
              name: `${profile.name} (Copy)`,
              createdAt: new Date(),
              updatedAt: new Date(),
              isDefault: false,
            });
          }
        });
        return newId;
      },

      exportProfile: (id) => {
        const profile = get().profiles.find((p) => p.id === id);
        if (profile) {
          return JSON.stringify(profile, null, 2);
        }
        return '';
      },

      importProfile: (data) => {
        try {
          const profile = JSON.parse(data) as SettingsProfile;
          const id = generateId();
          set((state) => {
            state.profiles.push({
              ...profile,
              id,
              createdAt: new Date(),
              updatedAt: new Date(),
              isDefault: false,
            });
          });
          return id;
        } catch {
          return null;
        }
      },

      // ═════════════════════════════════════════════════════════════════════════
      // VALIDATION
      // ═════════════════════════════════════════════════════════════════════════

      validateSettings: () => {
        const state = get();
        const errors: ValidationResult['errors'] = [];
        const warnings: ValidationResult['warnings'] = [];

        // Validate download settings
        if (state.settings.download.maxConcurrentDownloads < 1 || state.settings.download.maxConcurrentDownloads > 10) {
          errors.push({ path: 'download.maxConcurrentDownloads', message: 'Must be between 1 and 10' });
        }
        if (state.settings.download.timeout < 10) {
          warnings.push({ path: 'download.timeout', message: 'Very short timeout may cause failures' });
        }

        // Validate network settings
        if (state.settings.network.useProxy && !state.settings.network.proxy) {
          errors.push({ path: 'network.proxy', message: 'Proxy URL is required when proxy is enabled' });
        }

        // Validate theme settings
        if (state.settings.theme.fontScale < 0.5 || state.settings.theme.fontScale > 2) {
          errors.push({ path: 'theme.fontScale', message: 'Must be between 0.5 and 2' });
        }

        return { valid: errors.length === 0, errors, warnings };
      },

      validateCategory: (category) => {
        const state = get();
        const errors: ValidationResult['errors'] = [];
        const warnings: ValidationResult['warnings'] = [];

        switch (category) {
          case 'download':
            if (state.settings.download.maxConcurrentDownloads < 1 || state.settings.download.maxConcurrentDownloads > 10) {
              errors.push({ path: 'download.maxConcurrentDownloads', message: 'Must be between 1 and 10' });
            }
            break;
          case 'network':
            if (state.settings.network.useProxy && !state.settings.network.proxy) {
              errors.push({ path: 'network.proxy', message: 'Proxy URL is required when proxy is enabled' });
            }
            break;
          case 'theme':
            if (state.settings.theme.fontScale < 0.5 || state.settings.theme.fontScale > 2) {
              errors.push({ path: 'theme.fontScale', message: 'Must be between 0.5 and 2' });
            }
            break;
        }

        return { valid: errors.length === 0, errors, warnings };
      },

      // ═════════════════════════════════════════════════════════════════════════
      // KEYBOARD SHORTCUTS
      // ═════════════════════════════════════════════════════════════════════════

      registerShortcut: (shortcut) => {
        const id = `shortcut_${Date.now()}`;
        set((state) => {
          state.settings.shortcuts.shortcuts.push({ ...shortcut, id });
        });
        return id;
      },

      updateShortcut: (id, updates) => {
        set((state) => {
          const index = state.settings.shortcuts.shortcuts.findIndex((s) => s.id === id);
          if (index !== -1) {
            state.settings.shortcuts.shortcuts[index] = {
              ...state.settings.shortcuts.shortcuts[index],
              ...updates,
            };
          }
        });
      },

      removeShortcut: (id) => {
        set((state) => {
          state.settings.shortcuts.shortcuts = state.settings.shortcuts.shortcuts.filter((s) => s.id !== id);
        });
      },

      resetShortcuts: () => {
        set((state) => {
          state.settings.shortcuts.shortcuts = deepClone(DEFAULT_APP_SETTINGS.shortcuts.shortcuts);
        });
      },

      getShortcutByKey: (key, modifiers) => {
        const state = get();
        const sortedModifiers = [...modifiers].sort();
        return state.settings.shortcuts.shortcuts.find((s) => {
          const shortcutModifiers = [...s.modifiers].sort();
          return s.key.toLowerCase() === key.toLowerCase() &&
            JSON.stringify(shortcutModifiers) === JSON.stringify(sortedModifiers);
        });
      },

      // ═════════════════════════════════════════════════════════════════════════
      // THEME
      // ═════════════════════════════════════════════════════════════════════════

      setThemeMode: (mode) => {
        set((state) => {
          state.settings.theme.mode = mode;
          state.isDirty = true;
        });
      },

      setAccentColor: (color) => {
        set((state) => {
          state.settings.theme.accentColor = color;
          state.settings.theme.customColors.primary = color;
          state.isDirty = true;
        });
      },

      setCustomColor: (name, color) => {
        set((state) => {
          state.settings.theme.customColors[name] = color;
          state.isDirty = true;
        });
      },

      resetTheme: () => {
        set((state) => {
          state.settings.theme = deepClone(DEFAULT_APP_SETTINGS.theme);
          state.isDirty = true;
        });
      },

      exportTheme: () => {
        return JSON.stringify(get().settings.theme, null, 2);
      },

      importTheme: (data) => {
        try {
          const theme = JSON.parse(data) as ThemeSettings;
          set((state) => {
            state.settings.theme = theme;
            state.isDirty = true;
          });
          return true;
        } catch {
          return false;
        }
      },

      // ═════════════════════════════════════════════════════════════════════════
      // NOTIFICATIONS
      // ═════════════════════════════════════════════════════════════════════════

      updateNotificationSettings: (updates) => {
        set((state) => {
          state.settings.notifications = {
            ...state.settings.notifications,
            ...updates,
          };
          state.isDirty = true;
        });
      },

      testNotification: () => {
        if (typeof window !== 'undefined' && 'Notification' in window) {
          if (Notification.permission === 'granted') {
            new Notification('RS Toolkit Test', {
              body: 'Notification settings are working correctly!',
              icon: '/favicon.ico',
            });
          } else if (Notification.permission !== 'denied') {
            Notification.requestPermission().then((permission) => {
              if (permission === 'granted') {
                new Notification('RS Toolkit Test', {
                  body: 'Notification settings are working correctly!',
                  icon: '/favicon.ico',
                });
              }
            });
          }
        }
      },

      // ═════════════════════════════════════════════════════════════════════════
      // PERSISTENCE
      // ═════════════════════════════════════════════════════════════════════════

      markSaved: () => {
        set((state) => {
          state.isDirty = false;
          state.lastSaved = new Date();
        });
      },

      saveToStorage: () => {
        set((state) => {
          state.lastSaved = new Date();
        });
      },

      loadFromStorage: () => {
        set((state) => {
          state.isHydrated = true;
        });
      },

      exportSettings: () => {
        return JSON.stringify({
          settings: get().settings,
          profiles: get().profiles,
          exportedAt: new Date().toISOString(),
          version: '3.2.0',
        }, null, 2);
      },

      importSettings: (data) => {
        try {
          const parsed = JSON.parse(data);
          set((state) => {
            if (parsed.settings) {
              state.settings = { ...deepClone(DEFAULT_APP_SETTINGS), ...parsed.settings };
            }
            if (parsed.profiles) {
              state.profiles = parsed.profiles;
            }
            state.isDirty = true;
          });
          return true;
        } catch {
          return false;
        }
      },

      // ═════════════════════════════════════════════════════════════════════════
      // UNDO/REDO
      // ═════════════════════════════════════════════════════════════════════════

      undo: () => {
        const state = get();
        if (state.undoStack.length === 0) return false;

        const previousState = state.undoStack[state.undoStack.length - 1];
        
        set((s) => {
          s.redoStack.push(createUndoSnapshot(s.settings, 'redo'));
          if (s.redoStack.length > s.maxUndoSteps) {
            s.redoStack.shift();
          }
          
          s.settings = { ...s.settings, ...previousState.settings };
          s.undoStack.pop();
        });

        return true;
      },

      redo: () => {
        const state = get();
        if (state.redoStack.length === 0) return false;

        const nextState = state.redoStack[state.redoStack.length - 1];
        
        set((s) => {
          s.undoStack.push(createUndoSnapshot(s.settings, 'undo'));
          if (s.undoStack.length > s.maxUndoSteps) {
            s.undoStack.shift();
          }
          
          s.settings = { ...s.settings, ...nextState.settings };
          s.redoStack.pop();
        });

        return true;
      },

      canUndo: () => get().undoStack.length > 0,
      canRedo: () => get().redoStack.length > 0,

      clearHistory: () => {
        set((state) => {
          state.undoStack = [];
          state.redoStack = [];
        });
      },

      // ═════════════════════════════════════════════════════════════════════════
      // HYDRATION
      // ═════════════════════════════════════════════════════════════════════════

      setHydrated: (hydrated) => {
        set((state) => {
          state.isHydrated = hydrated;
        });
      },
    })),
    {
      name: 'rs-toolkit-settings',
      storage: createJSONStorage(() => localStorage),
      partialize: (state) => ({
        settings: state.settings,
        profiles: state.profiles,
        activeProfileId: state.activeProfileId,
      }),
      onRehydrateStorage: () => (state) => {
        if (state) {
          state.isHydrated = true;
          state.lastSaved = new Date();
        }
      },
    }
  )
);

// ═══════════════════════════════════════════════════════════════════════════════
// SELECTORS
// ═══════════════════════════════════════════════════════════════════════════════

export const selectSettings = (state: SettingsStore) => state.settings;
export const selectDownloadSettings = (state: SettingsStore) => state.settings.download;
export const selectThemeSettings = (state: SettingsStore) => state.settings.theme;
export const selectNotificationSettings = (state: SettingsStore) => state.settings.notifications;
export const selectShortcuts = (state: SettingsStore) => state.settings.shortcuts;
export const selectUISettings = (state: SettingsStore) => state.settings.ui;
export const selectNetworkSettings = (state: SettingsStore) => state.settings.network;
export const selectSecuritySettings = (state: SettingsStore) => state.settings.security;
export const selectProfiles = (state: SettingsStore) => state.profiles;
export const selectIsDirty = (state: SettingsStore) => state.isDirty;

export default useSettingsStore;
